################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Practical1/Practical_1A/Application/User/Core \
Practical1/Practical_1A/Application/User/Startup \
Practical1/Practical_1A/Core/Inc \
Practical1/Practical_1A/Core/Src \
Practical1/Practical_1A/Drivers/STM32F0xx_HAL_Driver/Src \
Practical1/Practical_1A/STM32CubeIDE/Application/User/Core \
Practical1/Practical_1A/STM32CubeIDE/Application/User/Startup \
Practical1/Practical_1A/build \
Practical1/Practical_1A \
Practical1/Practical_1B/Core/Src \
Practical1/Practical_1B/Drivers/CMSIS/Core/Template/ARMv8-M \
Practical1/Practical_1B/Drivers/CMSIS/Core_A/Source \
Practical1/Practical_1B/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/src \
Practical1/Practical_1B/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/GCC \
Practical1/Practical_1B/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform \
Practical1/Practical_1B/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Source/CommonTables \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Source/ControllerFunctions \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Source/FastMathFunctions \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Source/FilteringFunctions \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Source/MatrixFunctions \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Source/SupportFunctions \
Practical1/Practical_1B/Drivers/CMSIS/DSP/Source/TransformFunctions \
Practical1/Practical_1B/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/arm \
Practical1/Practical_1B/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/gcc \
Practical1/Practical_1B/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/iar \
Practical1/Practical_1B/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates \
Practical1/Practical_1B/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10 \
Practical1/Practical_1B/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru \
Practical1/Practical_1B/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test \
Practical1/Practical_1B/Drivers/CMSIS/NN/Source/ActivationFunctions \
Practical1/Practical_1B/Drivers/CMSIS/NN/Source/ConvolutionFunctions \
Practical1/Practical_1B/Drivers/CMSIS/NN/Source/FullyConnectedFunctions \
Practical1/Practical_1B/Drivers/CMSIS/NN/Source/NNSupportFunctions \
Practical1/Practical_1B/Drivers/CMSIS/NN/Source/PoolingFunctions \
Practical1/Practical_1B/Drivers/CMSIS/NN/Source/SoftmaxFunctions \
Practical1/Practical_1B/Drivers/CMSIS/RTOS2/Source \
Practical1/Practical_1B/Drivers/CMSIS/RTOS2/Template \
Practical1/Practical_1B/Drivers/STM32F0xx_HAL_Driver/Src \
Practical1/Practical_1B/build \
Practical1/Practical_1B \
Practical2/Core/Src \
Practical2/Drivers/CMSIS/Core/Template/ARMv8-M \
Practical2/Drivers/CMSIS/Core_A/Source \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/src \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCC \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCLANG \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/GCC \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/basic_math_tests \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/complex_math_tests \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/controller_tests \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/fast_math_tests \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/filtering_tests \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/intrinsics_tests \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/matrix_tests \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/statistics_tests \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/support_tests \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/transform_tests \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/BasicMathFunctions \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ComplexMathFunctions \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ControllerFunctions \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FastMathFunctions \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FilteringFunctions \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/HelperFunctions \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/Intrinsics \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/MatrixFunctions \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/StatisticsFunctions \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/SupportFunctions \
Practical2/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/TransformFunctions \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Practical2/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
Practical2/Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Practical2/Drivers/CMSIS/DSP/Source/CommonTables \
Practical2/Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Practical2/Drivers/CMSIS/DSP/Source/ControllerFunctions \
Practical2/Drivers/CMSIS/DSP/Source/FastMathFunctions \
Practical2/Drivers/CMSIS/DSP/Source/FilteringFunctions \
Practical2/Drivers/CMSIS/DSP/Source/MatrixFunctions \
Practical2/Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Practical2/Drivers/CMSIS/DSP/Source/SupportFunctions \
Practical2/Drivers/CMSIS/DSP/Source/TransformFunctions \
Practical2/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/arm \
Practical2/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/gcc \
Practical2/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/iar \
Practical2/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates \
Practical2/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10 \
Practical2/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru \
Practical2/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations \
Practical2/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test \
Practical2/Drivers/CMSIS/NN/Source/ActivationFunctions \
Practical2/Drivers/CMSIS/NN/Source/ConvolutionFunctions \
Practical2/Drivers/CMSIS/NN/Source/FullyConnectedFunctions \
Practical2/Drivers/CMSIS/NN/Source/NNSupportFunctions \
Practical2/Drivers/CMSIS/NN/Source/PoolingFunctions \
Practical2/Drivers/CMSIS/NN/Source/SoftmaxFunctions \
Practical2/Drivers/CMSIS/RTOS2/Source \
Practical2/Drivers/CMSIS/RTOS2/Template \
Practical2/Drivers/STM32F0xx_HAL_Driver/Src \
Practical2/build \
Practical2 \

